### ISSUE TITLE
This version does not compile with Glib version 2.23.

### ISSUE THREAD

**Issue by shreekant30** [ylatuya/gst-plugins-bad#2]
I have Glib version 2.23 installed on Ubuntu 16.04. When I type 'make' I get following error:
../../../gst-libs/gst/glib-compat-private.h:84:30: error: unknown type name ‘GStaticRecMutex’
 gst_g_static_rec_mutex_init (GStaticRecMutex *mutex)

How to solve this?
